name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Create dir
      uses: actions/checkout@v1
    - name: mkdir
      run: mkdir -p path/to/artifact
    - name: upload
    uses: actions/upload-artifact@master
    with:
   	 name: my-artifact
   	 path: path/to/artifact
        
